services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: rag_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/rag_data
    ports:
      - "5433:5432"
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U postgres -d rag_db"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5

  # backend:
  #   build: .
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   command: >
  #     sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"

volumes:
  postgres_data: