"""add tokens fields

Revision ID: eae6c1ed4878
Revises: d17c262899d9
Create Date: 2026-08-03 20:07:51.038047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eae6c1ed4878'
down_revision: Union[str, Sequence[str], None] = 'd17c262899d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('chat_messages', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'completion_tokens')
    op.drop_column('chat_messages', 'prompt_tokens')
    # ### end Alembic commands ###
